# Generated by Django 4.1.5 on 2023-01-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=33)),
                ('LastName', models.CharField(max_length=33)),
                ('Email', models.EmailField(max_length=33)),
                ('PassWord', models.CharField(max_length=33)),
            ],
        ),
    ]
